# HISTORY
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history
setopt HIST_IGNORE_ALL_DUPS NO_SHARE_HISTORY

# COMPLETION
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=long
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

autoload -U +X bashcompinit && bashcompinit

# PATH & ENVIRONMENT
path+=('/home/asim/.local/bin')
path+=('/usr/local/go/bin')

# Homebrew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
complete -o nospace -C "$(brew --prefix terraform)/bin/terraform" terraform

# fnm (node version manager)
FNM_PATH="/home/asim/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "$(fnm env)"
fi

# conda
__conda_setup="$('/home/asim/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/asim/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/asim/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/asim/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

eval "$(zoxide init zsh)"
eval "$(luarocks path --no-bin)"

# WezTerm (WSL path handling)
. /etc/profile.d/wezterm.sh

# ALIASES
alias vim="nvim"
alias pn=pnpm

# PLUGINS
source /home/linuxbrew/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /home/linuxbrew/.linuxbrew/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# PROMPT
eval "$(oh-my-posh init zsh --config 'https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/probua.minimal.omp.json')"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# SYNTAX HIGHLIGHTING (must be last)
source /home/linuxbrew/.linuxbrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

